### PR TITLE
Fixed rendering problem in preview with Android Studio

### PR DESCRIPTION
**Pull request by PureDark**
Simply check if is in edit mode , if so, gives a default value for stroke width

### CODE REVIEW

**Comment by hannesa2** [comment]
What's the point here ? I only see code format changes.
To do so, I recommend to check in code format settings and format all file at once

**Comment by hannesa2** [comment]
Hmm, in "Files Changed" tab I only see code format.
But looking at separated commits, there are more changes. When I see 4 commits, I guess you fought with git 😀

**Comment by dmytrodanylyk** [comment]
This is spam, related to this event https://blog.domenic.me/hacktoberfest/

**Comment by hannesa2** [comment]
It's 6 years old, I close it

**Pull request closed without merging**
